# Generated by Django 5.2.1 on 2025-06-08 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_categoria_tarefas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tarefas.categoria'),
        ),
    ]
