version: '3.9'
services:
  db:
    image: postgres:16
    container_name: postgres_django
    environment:
      POSTGRES_DB: banco_tarefas
      POSTGRES_USER: user_tarefas
      POSTGRES_PASSWORD: senha_tarefas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
